pipeline:
  name: Run TI
  identifier: Run_TI
  projectIdentifier: CI_Demos_new_gitX
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Nofar_Github
        repoName: jhttp
        build: <+input>
        sslVerify: false
        prCloneStrategy: MergeCommit
  stages:
    - stage:
        name: Build Test and Push
        identifier: Test_Build_and_Push
        description: hello world java demo
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: RunTests
                  description: run unit tests
                  name: runTestsWithIntelligence
                  identifier: runTestsWithIntelligence
                  timeout: 30m
                  spec:
                    connectorRef: account.nofar_dockerhub
                    image: maven:3.5.2-jdk-8-alpine
                    language: Java
                    buildTool: Maven
                    args: test
                    packages: io.harness.
                    runOnlySelectedTests: true
                    postCommand: mvn package -DskipTests
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    resources:
                      limits:
                        memory: 5000Mi
                        cpu: "1"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push image to DockerHub
                  identifier: Build_and_push_image_to_DockerHub
                  spec:
                    connectorRef: account.nofar_dockerhub
                    repo: bluebbb/javademo
                    tags:
                      - <+pipeline.sequenceId>
                    optimize: true
              - step:
                  type: Run
                  name: echo
                  identifier: echo
                  spec:
                    connectorRef: account.nofar_dockerhub
                    image: <+input>
                    shell: Sh
                    command: echo "hello"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8scluster
              namespace: harness-delegate-pmdemo
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          sharedPaths:
            - /additiona/path
  variables: []
