connector:
  name: BS1223
  identifier: BS1223
  description:
  orgIdentifier: default
  projectIdentifier: Product_Demos_CIE
  type: Github
  spec:
    url: https://github.com/keen-software
    validationRepo: jhttp
    authentication:
      type: Http
      spec:
        type: UsernamePassword
        spec:
          username: nofarb
          passwordRef: account.nofar_github_token
    apiAccess:
      type: Token
      spec:
        tokenRef: account.nofar_github_token
    type: Account
