pipeline:
    name: demo_1
    identifier: demo_1
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: basic
              identifier: basic
              description: ""
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: aaaaa
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: aaa
                                identifier: aaa
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    command: echo "hey"
                                    privileged: false
              variables: []
