inputSet:
  identifier: "IS1"
  name: "IS1"
  orgIdentifier: "default"
  projectIdentifier: "Product_Demos_CIE"
  pipeline:
    identifier: "java_http_client"
    properties:
      ci:
        codebase:
          build:
            type: "branch"
            spec:
              branch: "master"
    stages:
    - stage:
        identifier: "Test_Build_and_Push"
        type: "CI"
        spec:
          execution:
            steps:
            - step:
                identifier: "show_programming_language"
                type: "Run"
                description: "java"
